export const recipe = [
  {
    id: 1,
    name: "Spicy Chicken Tacos",
    images: [
      "https://www.hiddenvalley.com/wp-content/uploads/2021/04/spicy-ranch-chicken-tacos-RDP.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYZh6-0WaClwdXx0HrLQ4D399Ry-BR6wdZj2WhXgOs6nrATO1WCTdyOfhanJXCPEBuw0k&usqp=CAU",
      "https://gimmedelicious.com/wp-content/uploads/2019/01/Quick-Chicken-Tacos-food-truck-style-9-500x500.jpg",
    ],
    ingredients: [
      "2 boneless chicken breasts",
      "1 tablespoon chili powder",
      "1 teaspoon cumin",
      "1/2 teaspoon paprika",
      "1/4 teaspoon cayenne pepper",
      "Salt and pepper to taste",
      "4 small flour tortillas",
      "1 cup shredded lettuce",
      "1/2 cup diced tomatoes",
      "1/4 cup diced red onion",
      "1/4 cup sour cream",
    ],
    instructions: [
      "Season chicken with chili powder, cumin, paprika, cayenne, salt, and pepper.",
      "Grill or pan-fry chicken until cooked through.",
      "Slice chicken into thin strips.",
      "Warm tortillas in a dry pan.",
      "Assemble tacos with chicken, lettuce, tomatoes, red onion, and a dollop of sour cream.",
    ],
    rate: 4.5,
  },
  {
    id: 2,
    name: "Pasta Primavera",
    images: [
      "https://www.twopeasandtheirpod.com/wp-content/uploads/2019/05/Pasta-Primavera-3.jpg",
      "https://www.recipetineats.com/wp-content/uploads/2022/10/Pasta-Primavera-recipe_9.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7ViIdtqXGfXy3mypoqV2nJNem3l8XKcR1L4OWNITvg1fTWGkL_dxeS1C7EuQD2Lsux3k&usqp=CAU",
    ],
    ingredients: [
      "8 oz spaghetti",
      "1 cup broccoli florets",
      "1 cup sliced bell peppers",
      "1 cup cherry tomatoes",
      "1/2 cup sliced zucchini",
      "2 cloves garlic, minced",
      "2 tablespoons olive oil",
      "1/4 cup grated Parmesan cheese",
    ],
    instructions: [
      "Cook pasta according to package instructions.",
      "In a large pan, sauté garlic in olive oil.",
      "Add broccoli, bell peppers, cherry tomatoes, and zucchini. Cook until tender.",
      "Toss cooked pasta with the vegetable mixture.",
      "Sprinkle with Parmesan cheese before serving.",
    ],
    rate: 5,
  },
  {
    id: 3,
    name: "Grilled Salmon with Lemon Butter",
    images: [
      "https://themom100.com/wp-content/uploads/2022/11/salmon-with-lemon-butter-sauce-3393.jpg",
      "https://thelemonbowl.com/wp-content/uploads/2023/07/Grilled-salmon-with-lemon-garlic-sauce-scaled.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnZ8PMOu04R-mLCBB1I74oFjOsVZLobgfALt_DkZNtlM30ZVtNM6zqZxVcz6Ve3bfGDkw&usqp=CAU",
    ],
    ingredients: [
      " 2 salmon fillets",
      "2 tablespoons melted butter",
      "1 lemon, juiced and zested",
      "2 cloves garlic, minced",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat the grill.",
      "In a small bowl, mix melted butter, lemon juice, lemon zest, garlic, salt, and pepper.",
      "Brush salmon fillets with the lemon butter mixture.",
      "Grill salmon for about 5-7 minutes on each side, or until cooked through.",
    ],
    rate: 4,
  },
  {
    id: 4,
    name: "Mango Salsa",
    images: [
      "https://www.simplyrecipes.com/thmb/QUGG14kk81vj3LTjhhJD-XQDjfM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2006__08__mango-salsa-horiz-a-1600-9c2c6ed39e4740f19cea1496bf2d6554.jpg",
      "https://assets.bonappetit.com/photos/62f569017f72a713e35e3013/1:1/w_2560%2Cc_limit/0811-mango-salsa-recipe-lede.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/190410-mango-salsa-092-1555947798.jpg?crop=0.670xw:1.00xh;0.167xw,0&resize=1200:*",
    ],
    ingredients: [
      " 2 ripe mangoes, diced",
      "1/2 red onion, finely chopped",
      "1 red bell pepper, diced",
      "1/4 cup chopped fresh cilantro",
      "1 lime, juiced",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a bowl, combine mangoes, red onion, red bell pepper, and cilantro.",
      "Squeeze lime juice over the mixture.",
      "Season with salt and pepper. Chill before serving.",
    ],
    rate: 4.7,
  },
  {
    id: 5,
    name: "Caprese Salad",
    images: [
      "https://www.thespruceeats.com/thmb/2pjgFA7_nbZtlXr68BECvf6fO48=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/caprese-salad-tomato-salad-2217097-hero-03-75a0b89b30aa4a52b10fe4fdd9abfeb5.jpg",
      "https://www.seriouseats.com/thmb/5kQKbm3V-zgurSr95PTITqaS_vs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/classic-caprese-salad-recipe-hero-05_1-9ce2f9b0601c45279e07320f9548fa66.JPG",
      "https://hips.hearstapps.com/thepioneerwoman/wp-content/uploads/2011/06/caprese1.jpg",
    ],
    ingredients: [
      "4 large ripe tomatoes, sliced",
      "8 oz fresh mozzarella cheese, sliced",
      "1/4 cup fresh basil leaves",
      "2 tablespoons extra-virgin olive oil",
      "Balsamic glaze (optional)",
    ],
    instructions: [
      " Alternate tomato, mozzarella, and basil slices on a platter.",
      "Drizzle with olive oil and balsamic glaze if desired.",
    ],
    rate: 3.5,
  },
  {
    id: 6,
    name: "Stir-Fried Vegetable Noodles",
    images: [
      "https://uploads-ssl.webflow.com/5937d667a1e78f72396a4b9c/5b73f16ff794794a0920369c_IMG_1580.JPG",
      "https://www.seriouseats.com/thmb/8ezPmz2rs-GYkyyO6wI2em0dGco=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2014__06__2021-02-12-Lo-Mein-MHOM-9-90ee93b22d554f729e69497190524afd.jpg",
      "https://www.ambitiouskitchen.com/wp-content/uploads/2021/04/Vegan-Stir-Fry-Sesame-Noodles-7.jpg",
    ],
    ingredients: [
      "8 oz egg noodles",
      "2 cups mixed stir-fry vegetables",
      "2 tablespoons soy sauce",
      "1 tablespoon sesame oil",
      "1 clove garlic, minced",
      "1/2 teaspoon ginger, minced",
    ],
    instructions: [
      "Cook noodles according to package instructions.",
      "In a wok or large pan, stir-fry vegetables, garlic, and ginger.",
      "Add cooked noodles and drizzle with soy sauce and sesame oil.",
    ],
    rate: 5,
  },
  {
    id: 7,
    name: "Classic Caesar Salad",
    images: [
      "https://valentinascorner.com/wp-content/uploads/2021/05/caesar-salad-1-of-1.jpg",
      "https://www.simplyrecipes.com/thmb/j0ddRCJrN78xVUXQ1qKqfohVo0A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Caesar-Salad-LEAD-07-01d96a42f43941748b81d910a10888cd.jpg",
      "https://emeals-menubuilder.s3.amazonaws.com/v1/recipes/788812/pictures/large_theking-classic-caesar-salad.jpg",
    ],
    ingredients: [
      "1 head of romaine lettuce, chopped",
      "1/2 cup croutons",
      "1/4 cup grated Parmesan cheese",
      "Caesar dressing",
    ],
    instructions: [
      "Toss romaine lettuce with Caesar dressing.",
      "Top with croutons and Parmesan cheese.",
    ],
    rate: 5,
  },
  {
    id: 8,
    name: "Lemon Blueberry Pancakes",
    images: [
      "https://disheswithdad.com/wp-content/uploads/2020/04/lemon-blueberry-pancakes-3.jpg",
      "https://valentinascorner.com/wp-content/uploads/2021/07/Blueberry-Pancakes-1.jpg",
      "https://www.ambitiouskitchen.com/wp-content/uploads/2022/04/Fluffiest-Lemon-Blueberry-Poppyseed-Pancakes-5.jpg",
    ],
    ingredients: [
      "1 cup all-purpose flour",
      "2 tablespoons sugar",
      "1 teaspoon baking powder",
      "1/2 teaspoon baking soda",
      "1/4 teaspoon salt",
      "1 cup buttermilk",
      "1 egg",
      "2 tablespoons melted butter",
      "Zest of 1 lemon",
      "1/2 cup fresh blueberries",
    ],
    instructions: [
      "In a bowl, whisk together flour, sugar, baking powder, baking soda, and salt.",
      "In another bowl, mix buttermilk, egg, melted butter, and lemon zest.",
      "Combine wet and dry ingredients, then gently fold in blueberries.",
      "Cook spoonfuls of batter on a hot griddle until golden brown.",
    ],
    rate: 5,
  },
];
